# [Database]
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://horton.elephantsql.com:5432/[INSERT YOUR DATABASE NAME HERE]
    username: [INSERT YOUR USERNAME HERE]
    password: [INSERT YOUR DATABASE PASSWORD HERE]
    max-active: 2
    ddl-auto: update
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
